title: My Hopeful Future Blog
author: Brandy Hudgins
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My blog will feature reviews and booklists wiht a with a focus on fantasy

# social links
twitter_username: your-twitter-handle
github_username:  bhudgins

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

